/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class QuestionBankTest {

    @Test
    public void markJavaQuestionTest() throws Exception {
        QuestionBank questionBank = new QuestionBank();
        String usersAnswer = "public class Hello {\n  public static void main(String[] args) {\n    System.out.println(\"Hello, World!\");\n  }\n}";
        String questionID = "14";
        String userId = "22751096";
        String attempt = "1";
        String language = "Java";

        String[] result = questionBank.markProgrammingQuestion(usersAnswer, questionID, userId, attempt, language);
        String[] expectedResult = new String[] { userId, questionID, "3", "Correct!" };

        assertArrayEquals(expectedResult, result);

        attempt = "2";
        result = questionBank.markProgrammingQuestion(usersAnswer, questionID, userId, attempt, language);
        expectedResult = new String[] { userId, questionID, "2", "Correct!" };
        assertArrayEquals(expectedResult, result);

        attempt = "3";
        result = questionBank.markProgrammingQuestion(usersAnswer, questionID, userId, attempt, language);
        expectedResult = new String[] { userId, questionID, "1", "Correct!" };
        assertArrayEquals(expectedResult, result);

        attempt = "3";
        usersAnswer = "";
        result = questionBank.markProgrammingQuestion(usersAnswer, questionID, userId, attempt, language);
        System.out.println(result);
        String correctCode = "public class HelloWorld {\n  public static void main(String[] args) {\n    System.out.println(\"Hello, World!\");\n  }\n}";
        expectedResult = new String[] { userId, questionID, "0", "Incorrect! The correct answer was: " + correctCode };
        assertArrayEquals(expectedResult, result);
    }
}
